dinos_app/config/routes.rb
Rails.application.routes.draw do
  resources :dinos, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :welcome, only: [:index, :show]

  root 'welcome#index'
end

dinos_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dinos_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

dinos_app/app/controllers/dinos_controller.rb
class DinosController < ApplicationController
  def index
  end

  def show
  end
end

dinos_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def show
    @name = params[:id]*3
  end
end

dinos_app/app/helpers/application_helper.rb
module ApplicationHelper
end

dinos_app/app/helpers/dinos_helper.rb
module DinosHelper
end

dinos_app/app/views/dinos/index.html.erb
<h1>Aye Welcome to Dinos Index Page</h1>
<p>Find me in app/views/dinos/index.html.erb</p>

dinos_app/app/views/dinos/show.html.erb
<h1>We are Showing Dinos!</h1>
<p>Find me in app/views/dinos/show.html.erb</p>

dinos_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinosApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>This is the Header written into the application.html</header>
    <%= yield %>
  </body>
</html>

dinos_app/app/views/welcome/index.html.erb
<h1>Welcome To the Index.html</h1>

<%= link_to 'Go to Dinos', dinos_path%>

dinos_app/app/views/welcome/show.html.erb
<h1>Aye, <%= @name  %> </h1>